name: "Deploy documentation to website"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate_documentation:
    name: "Regenerate documentation website"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        graalvm-version: [ dev ]
        java-version: [ 11 ]
        os: [ ubuntu-20.04 ]
    steps:
      - uses: ./.github/actions/prepare-environment
        with:
          push-access: 1
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "🌍 Build and publish documentation"
        run: |
          ./gradlew :docs:gitPublishPush
